### ISSUE TITLE
f2017170101 - Database Structure

### ISSUE THREAD

**Issue by st0yanov** [veskoy/gomas#14]
**Feature description:**
Plan the database structure and create appropriate package in the project structure.

**Tasks:**
- [x] Plan the database structure
- [x] Create package in the project structure
- [x] Write simple definitions with documentation of the desired functionality (no implementation for now).
