### ISSUE TITLE
f2017100201 - Add Ginkgo & Gomega for BDD

### ISSUE THREAD

**Issue by st0yanov** [veskoy/gomas#19]
**Feature description:**
Add Ginkgo & Gomega for easier testing and behaviour driven development.

**Tasks:**
- [ ] Add Ginkgo & Gomega
- [ ] Rewrite tests in the new style
- [ ] Make sure CI server runs the new tests correctly
