### ISSUE TITLE
f2017100201 - Add Ginkgo & Gomega for BDD

### ISSUE THREAD

**Issue by st0yanov** [veskoy/gomas#20]
**Feature description:**
Add Ginkgo & Gomega for easier testing and behaviour driven development.

**Tasks:**
- [x] Add Ginkgo & Gomega
- [x] Rewrite tests in the new style
- [x] Make sure CI server runs the new tests correctly
